spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgress
    url: jdbc:postgress://localhost:puerto/juandavidcadavid
    username: juandavidcadavid
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /test
  port: 9080

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
